# -*- coding: utf-8 -*-
"""NWJ-FYP_V8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l325eZfDIG7x8GV2S0s9Q2GuS406GwCE

Data Pre-processing
"""

import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# 1. Load the Dataset (Ensure fanuc_data(Data)2.csv is uploaded to your Colab files panel)
df = pd.read_csv('fanuc_data(Data)2.csv')

# 2. Setup Telemetry Feature Framework (13 mechatronic features)
features = ['J1_pos', 'J2_pos', 'J3_pos', 'J4_pos', 'J5_pos', 'J6_pos',
            'J1_torque', 'J2_torque', 'J3_torque', 'J4_torque', 'J5_torque', 'J6_torque',
            'program_speed']
X = df[features]
y = df['Status']

# 3. Label Encoding
le = LabelEncoder()
y_encoded = le.fit_transform(y)
np.save('label_classes.npy', le.classes_)

# 4. Stratified Split (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded)

# 5. Standard Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 6. Save Arrays and Scaler Objects to local environment
joblib.dump(scaler, 'telemetry_scaler.pkl')
np.save('X_train_scaled.npy', X_train_scaled)
np.save('y_train.npy', y_train)
np.save('X_test_scaled.npy', X_test_scaled)
np.save('y_test.npy', y_test)
X_test.to_csv('X_test_raw.csv', index=False)

print("="*50)
print("PART 1: PREPROCESSING COMPLETED & SCALER EXPORTED")
print("="*50)
print(f"Training features shape : {X_train_scaled.shape}")
print(f"Testing features shape  : {X_test_scaled.shape}")

"""Training"""

import numpy as np
import joblib
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# 1. Load Preprocessed Training Pool
X_train_scaled = np.load('X_train_scaled.npy')
y_train = np.load('y_train.npy')

print("="*60)
print("PART 2: INITIALIZING CORE ALGORITHM BASELINE TRAINING")
print("="*60)

# A. Train & Save Support Vector Machine (SVM)
print("Training Support Vector Machine (SVM)...")
svm_model = SGDClassifier(loss='hinge', random_state=42, class_weight='balanced')
svm_model.fit(X_train_scaled, y_train)
joblib.dump(svm_model, 'svm_industrial_model.pkl')
print("-> SVM baseline trained and exported as 'svm_industrial_model.pkl'\n")

# B. Train & Save Random Forest
print("Training Random Forest Classifier...")
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced', n_jobs=-1)
rf_model.fit(X_train_scaled, y_train)
joblib.dump(rf_model, 'rf_industrial_model.pkl')
print("-> Random Forest trained and exported as 'rf_industrial_model.pkl'\n")

# C. Train & Save XGBoost
print("Training XGBoost Classifier...")
xgb_model = XGBClassifier(n_estimators=100, learning_rate=0.1, random_state=42, eval_metric='logloss', n_jobs=-1)
xgb_model.fit(X_train_scaled, y_train)
xgb_model.save_model('xgb_industrial_model.json')
print("-> XGBoost trained and exported as 'xgb_industrial_model.json'\n")

print("="*60)
print("ALL CORE BASELINE MODELS TRAINED AND EXPORTED SUCCESSFULLY")
print("="*60)

"""Testing"""

import numpy as np
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, matthews_corrcoef

# 1. Load Preprocessed Data
X_train_scaled = np.load('X_train_scaled.npy')
y_train = np.load('y_train.npy')
class_names = np.load('label_classes.npy', allow_pickle=True)

svm_model = joblib.load('svm_industrial_model.pkl')
rf_model = joblib.load('rf_industrial_model.pkl')
xgb_model = XGBClassifier()
xgb_model.load_model('xgb_industrial_model.json')

models = {
    "Support Vector Machine (SVM)": svm_model,
    "Random Forest Ensemble": rf_model,
    "XGBoost Classifier": xgb_model
}

train_confusion_matrices = {}

print("=" * 80)
print(f"INTERNAL DATA CHECK: Training Data Pool Size = {X_train_scaled.shape[0]} samples.")
print("=" * 80)

# 2. Performance Matrix Printout
for name, model in models.items():
    y_train_pred = model.predict(X_train_scaled)
    cm = confusion_matrix(y_train, y_train_pred)
    train_confusion_matrices[name] = cm
    mcc = matthews_corrcoef(y_train, y_train_pred)

    print(f"\n[TRAINING PERFORMANCE MATRIX]: {name.upper()}")
    print("-" * (29 + len(name)))
    print(classification_report(y_train, y_train_pred, target_names=class_names, digits=2))
    print(f"Training Matthews Correlation Coefficient (MCC): {mcc:.3f}")
    print("=" * 80)

# 3. Side-by-Side Plotting
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle("Model Evaluation Matrix: Training Dataset (80% Internal Pool)", fontsize=14, fontweight='bold')

for ax, (name, cm) in zip(axes, train_confusion_matrices.items()):
    sns.heatmap(
        cm, annot=True, fmt='d', cmap='Purples', cbar=False, ax=ax,
        xticklabels=class_names, yticklabels=class_names,
        annot_kws={'size': 14, 'weight': 'bold'}
    )
    ax.set_title(f"{name}", fontsize=11, fontweight='bold')
    ax.set_xlabel("Predicted Label", fontsize=10)
    ax.set_ylabel("True Ground Truth Label", fontsize=10)

plt.tight_layout()
plt.show()

"""Torque Ablation"""

import numpy as np
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix

# 1. Workspace Framework Setups
X_train_scaled = np.load('X_train_scaled.npy')
y_train = np.load('y_train.npy')
X_test_scaled = np.load('X_test_scaled.npy')
y_test = np.load('y_test.npy')
classes = np.load('label_classes.npy', allow_pickle=True)

features = ['J1_pos', 'J2_pos', 'J3_pos', 'J4_pos', 'J5_pos', 'J6_pos',
            'J1_torque', 'J2_torque', 'J3_torque', 'J4_torque', 'J5_torque', 'J6_torque', 'program_speed']
torque_features = ['J1_torque', 'J2_torque', 'J3_torque', 'J4_torque', 'J5_torque', 'J6_torque']

print("="*75)
print("   STARTING BATCH TRAINING FOR ALL 18 TORQUE ABLATION SUB-MODELS   ")
print("="*75)

# A. Retrain Ablation Combinations
for torque in torque_features:
    feat_indices = [features.index(f) for f in features if f != torque]
    X_train_ablated = X_train_scaled[:, feat_indices]

    svm_ab = SGDClassifier(loss='hinge', random_state=42, class_weight='balanced')
    svm_ab.fit(X_train_ablated, y_train)
    joblib.dump(svm_ab, f"svm_ignore_{torque}.pkl")

    rf_ab = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
    rf_ab.fit(X_train_ablated, y_train)
    joblib.dump(rf_ab, f"rf_ignore_{torque}.pkl")

    xgb_ab = XGBClassifier(n_estimators=100, learning_rate=0.1, random_state=42, eval_metric='logloss')
    xgb_ab.fit(X_train_ablated, y_train)
    xgb_ab.save_model(f"xgb_ignore_{torque}.json")

print("SUCCESS: Ablation variations cached successfully.")

# B. Construct 3x7 Global Comparison Plot Layout
ablation_scenarios = ['None (Baseline)'] + torque_features
svm_baseline = joblib.load('svm_industrial_model.pkl')
rf_baseline = joblib.load('rf_industrial_model.pkl')
xgb_baseline = XGBClassifier(); xgb_baseline.load_model('xgb_industrial_model.json')

baseline_models_dict = {"SVM": svm_baseline, "Random Forest": rf_baseline, "XGBoost": xgb_baseline}
models_list = ["SVM", "Random Forest", "XGBoost"]

fig, axes = plt.subplots(nrows=3, ncols=7, figsize=(24, 12))
for row_idx, model_name in enumerate(models_list):
    for col_idx, scenario in enumerate(ablation_scenarios):
        ax = axes[row_idx, col_idx]

        if scenario == 'None (Baseline)':
            y_pred = baseline_models_dict[model_name].predict(X_test_scaled)
        else:
            feat_indices = [features.index(f) for f in features if f != scenario]
            X_test_ablated = X_test_scaled[:, feat_indices]

            if model_name == "SVM":
                deployed_model = joblib.load(f"svm_ignore_{scenario}.pkl")
            elif model_name == "Random Forest":
                deployed_model = joblib.load(f"rf_ignore_{scenario}.pkl")
            elif model_name == "XGBoost":
                deployed_model = XGBClassifier(); deployed_model.load_model(f"xgb_ignore_{scenario}.json")
            y_pred = deployed_model.predict(X_test_ablated)

        cm = confusion_matrix(y_test, y_pred)
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False, ax=ax, xticklabels=classes, yticklabels=classes, annot_kws={"size": 12})

        if row_idx == 0:
            ax.set_title(f"Ignore: {scenario.split('_')[0]}", fontsize=14, fontweight='bold', pad=10)
        if col_idx == 0:
            ax.set_ylabel(f"{model_name}\n\nActual", fontsize=14, fontweight='bold')
        else:
            ax.set_ylabel("")
        ax.set_xlabel("Predicted", fontsize=10)

plt.suptitle("Feature Ablation Confusion Matrix Grid", fontsize=18, fontweight='bold', y=0.98)
plt.tight_layout()
plt.show()

"""Result"""

import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix

# 1. Reload Testing Data Pools & Scaler
X_test_scaled = np.load('X_test_scaled.npy')
y_test = np.load('y_test.npy')
X_test_raw = pd.read_csv('X_test_raw.csv')
classes = np.load('label_classes.npy', allow_pickle=True)

svm_model = joblib.load('svm_industrial_model.pkl')
rf_model = joblib.load('rf_industrial_model.pkl')
xgb_model = XGBClassifier(); xgb_model.load_model('xgb_industrial_model.json')

models_dict = {
    "SVM Baseline": svm_model,
    "Random Forest Ensemble": rf_model,
    "XGBoost Gradient Boosting": xgb_model
}

# ==========================================
# SUB-PART A: LOG TEST PERFORMANCE MATRICES
# ==========================================
print("="*80)
print("             DEPLOYMENT TESTING REPORT BREAKDOWNS             ")
print("="*80)

for model_name, model in models_dict.items():
    y_pred = model.predict(X_test_scaled)
    print(f"\n[Algorithm Testing Slices Deployment]: {model_name}")
    print(classification_report(y_test, y_pred, target_names=classes, digits=2))
    print("="*80)

# ==========================================
# SUB-PART B: RENDER STANDALONE TEST CMs DYNAMICALLY
# ==========================================
plt.rcParams['font.weight'] = 'bold'
plt.rcParams['axes.labelweight'] = 'bold'

for model_name, model in models_dict.items():
    y_pred = model.predict(X_test_scaled)
    cm = confusion_matrix(y_test, y_pred)

    fig, ax = plt.subplots(figsize=(5.5, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='GnBu', cbar=True, xticklabels=classes, yticklabels=classes,
                annot_kws={'size': 14, 'weight': 'bold'}, linewidths=1.5, linecolor='white', square=True)

    ax.set_title(f'{model_name} Test Confusion Matrix\n', fontsize=12, fontweight='bold')
    ax.set_xlabel('\nPredicted Condition Label', fontsize=11, fontweight='bold')
    ax.set_ylabel('Actual Ground Truth Label\n', fontsize=11, fontweight='bold')
    plt.tight_layout()
    plt.show()

# ==========================================
# SUB-PART C: EXTRACT PHYSICAL TORQUE WINDOW BOUNDARIES
# ==========================================
print("\n" + "="*115)
print("      EXTRACTED PHYSICAL TORQUE VALUE RANGES (Nm) THAT TRIGGERED ERROR CLASSIFICATIONS")
print("="*115)

torque_cols = ['J1_torque', 'J2_torque', 'J3_torque', 'J4_torque', 'J5_torque', 'J6_torque']

# Find what integer corresponds to 'Abnormal' or 'Error' status
error_label_string = 'Abnormal' if 'Abnormal' in list(classes) else 'Error'
error_val = list(classes).index(error_label_string)

boundary_records = []

for model_title, baseline_model in models_dict.items():
    short_name = "SVM" if "SVM" in model_title else ("Random Forest" if "Forest" in model_title else "XGBoost")
    preds = baseline_model.predict(X_test_scaled)

    # Filter only samples where the model predicted an anomaly state
    error_mask = (preds == error_val)
    error_frames = X_test_raw[error_mask]

    for t_axis in torque_cols:
        min_val = error_frames[t_axis].min() if len(error_frames) > 0 else np.nan
        max_val = error_frames[t_axis].max() if len(error_frames) > 0 else np.nan
        boundary_records.append({
            'Algorithm': short_name,
            'Torque Joint': t_axis.split('_')[0],
            'Min Torque Bound (Nm)': round(min_val, 4),
            'Max Torque Bound (Nm)': round(max_val, 4)
        })

boundary_df = pd.DataFrame(boundary_records)
final_table = boundary_df.pivot(index='Torque Joint', columns='Algorithm', values=['Min Torque Bound (Nm)', 'Max Torque Bound (Nm)'])

print(final_table.to_string())
final_table.to_csv('physical_error_ranges.csv')
print("\n-> CSV summary table successfully stored as 'physical_error_ranges.csv'")